import React from 'react';
import Head from "next/head";
import {NextPage} from "next";

const LandingHead : NextPage = () => {
    return (

          <Head>
              <title>موبوتست</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>

    );
};

export default LandingHead;